import { useState } from 'react';
import { Send, Phone, Loader2 } from 'lucide-react';
import {
	Dialog,
	DialogContent,
	DialogHeader,
	DialogTitle,
	DialogDescription,
	DialogFooter,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useWhatsAppSendDocument } from '@/query/whatsapp.query';

interface ShareViaWhatsAppProps {
	isOpen: boolean;
	onClose: () => void;
	documentBase64: string;
	fileName: string;
	totalPages: number;
}

export default function ShareViaWhatsApp({
	isOpen,
	onClose,
	documentBase64,
	fileName,
	totalPages,
}: ShareViaWhatsAppProps) {
	const [phoneNumber, setPhoneNumber] = useState('');
	const [customMessage, setCustomMessage] = useState('');

	const { mutate: sendDocument, isPending } = useWhatsAppSendDocument();

	const formatPhoneNumber = (value: string) => {
		const digits = value.replace(/\D/g, '');
		if (digits.startsWith('91') && digits.length > 10) {
			return digits;
		}
		if (digits.length > 10) {
			return digits;
		}
		return digits;
	};

	const handlePhoneChange = (e: React.ChangeEvent<HTMLInputElement>) => {
		const formatted = formatPhoneNumber(e.target.value);
		setPhoneNumber(formatted);
	};

	const getFullPhoneNumber = () => {
		const digits = phoneNumber.replace(/\D/g, '');
		if (digits.length === 10) {
			return `+91${digits}`;
		}
		if (digits.startsWith('91') && digits.length === 12) {
			return `+${digits}`;
		}
		if (!digits.startsWith('+')) {
			return `+${digits}`;
		}
		return digits;
	};

	const handleSend = () => {
		const fullPhone = getFullPhoneNumber();
		const defaultMessage = `Hi! I've analyzed ${totalPages} page(s) for SEO and prepared a detailed report. Please find the PDF attached.\n\nThis report includes:\n• Word count analysis\n• Image optimization checks\n• Meta description review\n• Heading structure analysis\n• Link analysis\n\nGenerated by SEO Rocket`;

		const message = customMessage.trim() || defaultMessage;

		sendDocument({
			phoneNumber: fullPhone,
			message,
			documentBase64,
			fileName,
			mimeType: 'application/pdf',
		}, {
			onSuccess: () => {
				onClose();
				setPhoneNumber('');
				setCustomMessage('');
			},
		});
	};

	const isValidPhone = () => {
		const digits = phoneNumber.replace(/\D/g, '');
		return digits.length >= 10;
	};

	return (
		<Dialog open={isOpen} onOpenChange={onClose}>
			<DialogContent className='sm:max-w-md'>
				<DialogHeader>
					<DialogTitle className='flex items-center gap-2'>
						<Send className='h-5 w-5 text-green-500' />
						Share Report via WhatsApp
					</DialogTitle>
					<DialogDescription>
						Send the SEO analysis PDF directly to a WhatsApp number.
						Default country code is +91 (India).
					</DialogDescription>
				</DialogHeader>

				<div className='space-y-4 py-4'>
					<div className='space-y-2'>
						<Label htmlFor='phone'>WhatsApp Number</Label>
						<div className='flex gap-2'>
							<div className='flex items-center justify-center px-3 bg-muted rounded-md border border-input text-sm font-medium min-w-[60px]'>
								+91
							</div>
							<Input
								id='phone'
								type='tel'
								placeholder='9876543210'
								value={phoneNumber}
								onChange={handlePhoneChange}
								className='flex-1'
								maxLength={10}
							/>
						</div>
						<p className='text-xs text-muted-foreground'>
							Enter 10-digit mobile number without country code
						</p>
					</div>

					<div className='space-y-2'>
						<Label htmlFor='message'>Custom Message (Optional)</Label>
						<textarea
							id='message'
							placeholder='Add a personal message...'
							value={customMessage}
							onChange={(e) => setCustomMessage(e.target.value)}
							className='w-full min-h-[100px] px-3 py-2 text-sm rounded-md border border-input bg-background resize-none focus:outline-none focus:ring-2 focus:ring-ring'
						/>
					</div>

					<div className='bg-muted/50 rounded-lg p-3 space-y-1'>
						<p className='text-xs font-medium text-muted-foreground'>Preview:</p>
						<p className='text-sm text-foreground/80 whitespace-pre-wrap'>
							{customMessage.trim() || `Hi! I've analyzed ${totalPages} page(s) for SEO and prepared a detailed report. Please find the PDF attached.`}
						</p>
						<p className='text-xs text-muted-foreground mt-2'>
							📎 {fileName}
						</p>
					</div>
				</div>

				<DialogFooter>
					<Button variant='outline' onClick={onClose} disabled={isPending}>
						Cancel
					</Button>
					<Button onClick={handleSend} disabled={!isValidPhone() || isPending}>
						{isPending ? (
							<>
								<Loader2 className='h-4 w-4 animate-spin mr-2' />
								Sending...
							</>
						) : (
							<>
								<Phone className='h-4 w-4 mr-2' />
								Send via WhatsApp
							</>
						)}
					</Button>
				</DialogFooter>
			</DialogContent>
		</Dialog>
	);
}
