import jsPDF from 'jspdf';
import type { ScrapedPageData } from '@/types/seo.types';

interface ReportResult {
	base64: string;
	fileName: string;
}

const buildPdfContent = (doc: jsPDF, results: ScrapedPageData[]): void => {
	const pageWidth = doc.internal.pageSize.getWidth();
	const margin = 20;
	let yPos = margin;

	const addNewPageIfNeeded = (requiredSpace: number) => {
		if (yPos + requiredSpace > doc.internal.pageSize.getHeight() - margin) {
			doc.addPage();
			yPos = margin;
		}
	};

	const addText = (text: string, fontSize: number, isBold: boolean = false) => {
		doc.setFontSize(fontSize);
		doc.setFont('helvetica', isBold ? 'bold' : 'normal');
		const lines = doc.splitTextToSize(text, pageWidth - margin * 2);
		addNewPageIfNeeded(lines.length * (fontSize * 0.4) + 4);
		doc.text(lines, margin, yPos);
		yPos += lines.length * (fontSize * 0.4) + 4;
	};

	const addDivider = () => {
		addNewPageIfNeeded(10);
		doc.setDrawColor(200, 200, 200);
		doc.line(margin, yPos, pageWidth - margin, yPos);
		yPos += 8;
	};

	doc.setFont('helvetica', 'bold');
	doc.setFontSize(20);
	doc.text('SEO Analysis Report', margin, yPos);
	yPos += 12;

	doc.setFont('helvetica', 'normal');
	doc.setFontSize(10);
	doc.setTextColor(128, 128, 128);
	doc.text(
		`Generated on: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' })}`,
		margin,
		yPos,
	);
	yPos += 12;
	doc.setTextColor(0, 0, 0);
	addDivider();

	const totalWords = results.reduce((sum, p) => sum + p.wordCount, 0);
	const totalImages = results.reduce((sum, p) => sum + p.images.length, 0);
	const totalImagesWithoutAlt = results.reduce(
		(sum, p) => sum + p.images.filter((img) => !img.alt).length,
		0,
	);
	const totalLinks = results.reduce(
		(sum, p) => sum + p.internalLinkCount + p.externalLinkCount,
		0,
	);
	const pagesWithMetaDesc = results.filter((p) => p.metaDescription).length;
	const pagesWithH1 = results.filter((p) => p.headings.h1.length > 0).length;

	addText('Summary', 14, true);
	yPos += 4;

	const stats = [
		`Total Pages Analyzed: ${results.length}`,
		`Total Words: ${totalWords.toLocaleString()}`,
		`Total Images: ${totalImages} (${totalImagesWithoutAlt} without alt text)`,
		`Total Links: ${totalLinks}`,
		`Pages with Meta Description: ${pagesWithMetaDesc} (${Math.round((pagesWithMetaDesc / results.length) * 100)}%)`,
		`Pages with H1: ${pagesWithH1} (${Math.round((pagesWithH1 / results.length) * 100)}%)`,
	];

	stats.forEach((stat) => {
		addText(`  • ${stat}`, 10);
	});

	addDivider();

	results.forEach((page, index) => {
		addNewPageIfNeeded(60);
		addText(`Page ${index + 1}: ${page.url}`, 12, true);
		yPos += 4;

		if (page.isError) {
			doc.setTextColor(220, 53, 69);
			addText('  [ERROR] This page could not be scraped', 10);
			doc.setTextColor(0, 0, 0);
			yPos += 8;
			return;
		}

		if (page.title) {
			addText(`  Title: ${page.title}`, 10);
		}
		if (page.metaDescription) {
			addText(`  Meta Description: ${page.metaDescription}`, 10);
		}
		addText(`  Word Count: ${page.wordCount.toLocaleString()}`, 10);
		addText(
			`  Images: ${page.images.length} (${page.images.filter((i) => !i.alt).length} without alt)`,
			10,
		);
		addText(`  Internal Links: ${page.internalLinkCount}`, 10);
		addText(`  External Links: ${page.externalLinkCount}`, 10);

		if (page.headings.h1.length > 0) {
			addText(`  H1 Tags (${page.headings.h1.length}):`, 10);
			page.headings.h1.forEach((h) => {
				addText(`    - ${h}`, 9);
			});
		}
		if (page.headings.h2.length > 0) {
			addText(`  H2 Tags (${page.headings.h2.length}):`, 10);
			page.headings.h2.slice(0, 5).forEach((h) => {
				addText(`    - ${h}`, 9);
			});
			if (page.headings.h2.length > 5) {
				addText(`    ... and ${page.headings.h2.length - 5} more`, 9);
			}
		}

		const missingAltImages = page.images.filter((img) => !img.alt);
		if (missingAltImages.length > 0) {
			yPos += 4;
			doc.setTextColor(220, 53, 69);
			addText(`  ⚠ Images Missing Alt Text (${missingAltImages.length}):`, 10);
			missingAltImages.slice(0, 5).forEach((img) => {
				const src = img.src || 'Unknown';
				addText(
					`    - ${src.substring(0, 60)}${src.length > 60 ? '...' : ''}`,
					8,
				);
			});
			doc.setTextColor(0, 0, 0);
		}
		if (!page.metaDescription) {
			yPos += 4;
			doc.setTextColor(220, 53, 69);
			addText('  ⚠ Missing Meta Description', 10);
			doc.setTextColor(0, 0, 0);
		}
		if (page.headings.h1.length === 0) {
			yPos += 4;
			doc.setTextColor(220, 53, 69);
			addText('  ⚠ Missing H1 Tag', 10);
			doc.setTextColor(0, 0, 0);
		}

		if (index < results.length - 1) {
			addDivider();
		}
	});

	addNewPageIfNeeded(30);
	yPos = doc.internal.pageSize.getHeight() - margin;
	doc.setFontSize(8);
	doc.setTextColor(128, 128, 128);
	doc.text('Generated by SEO Rocket', margin, yPos);
	yPos += 4;
	doc.text('This report is for informational purposes only.', margin, yPos);
};

export const generateSeoReport = (results: ScrapedPageData[]): void => {
	const doc = new jsPDF();
	buildPdfContent(doc, results);
	doc.save(`seo-report-${Date.now()}.pdf`);
};

export const generateSeoReportBase64 = (results: ScrapedPageData[]): ReportResult => {
	const doc = new jsPDF();
	buildPdfContent(doc, results);
	const fileName = `seo-report-${Date.now()}.pdf`;
	const dataUri = doc.output('datauristring');
	const base64 = dataUri.split(',')[1];
	return { base64, fileName };
};
